networks:
  default:
    name: 'skuf'

volumes:
  skuf-postgres:

services:
  postgres:
    container_name: 'skuf-postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "skuf"
      POSTGRES_USER: "sqladmin"
      POSTGRES_PASSWORD: 'bnnvbrrdG557fygtse'
    volumes:
      - skuf-postgres:/var/lib/postgresql/data

  backend:
    container_name: 'skuf-backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://sqladmin:bnnvbrrdG557fygtse@postgres:5432/skuf"
    networks:
      - default

  frontend:
    container_name: 'skuf-frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - ./shared:/app/shared
    networks:
      - default