networks:
  default:
    name: 'skuf'

volumes:
  skuf-postgres:

services:
  postgres:
    container_name: 'skuf-postgres'
    image: 'postgres:latest'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: "skuf"
      POSTGRES_USER: "sqladmin"
      POSTGRES_PASSWORD: 'bnnvbrrdG557fygtse'
    volumes:
      - skuf-postgres:/var/lib/postgresql/data

  backend:
    container_name: 'skuf-backend'
    build:
      context: .
    image: varaking/skuf-backend:latest
    ports:
      - "80:3000"
    environment:
      DATABASE_URL: "postgresql://sqladmin:bnnvbrrdG557fygtse@109.68.213.18:5433/skuf"
    networks:
      - default
